# Generated by Django 4.2.16 on 2025-02-14 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scrum_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scrum_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
